# Generated by Django 4.0.6 on 2023-09-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/photo/%Y/%m/%d', verbose_name='Изображение программа')),
                ('name', models.CharField(max_length=500, verbose_name='Название программа')),
                ('info', models.CharField(max_length=1000, verbose_name='Описание')),
                ('link', models.CharField(max_length=1000, verbose_name='Ссылка источника')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
    ]
