# Generated by Django 4.2.11 on 2024-03-20 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0003_laborant_alter_about_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computers',
            options={'verbose_name': '11 Лаборант компьютер', 'verbose_name_plural': '11 Лаборант компьютеры'},
        ),
        migrations.AlterModelOptions(
            name='kabinet',
            options={'verbose_name': '10 Лаборант кабинет', 'verbose_name_plural': '10 Лаборант кабиненты'},
        ),
        migrations.AlterModelOptions(
            name='laborant',
            options={'verbose_name': '9 Лаборант', 'verbose_name_plural': '9 Лаборант'},
        ),
    ]
